library(readr)

news_orgs <-
  readr::read_csv(
    file = 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-05/news_orgs.csv',
    col_types = cols(
      publication_name = col_character(),
      parent_publication = col_character(),
      url = col_character(),
      owner = col_character(),
      is_owner_founder = col_character(),
      city = col_character(),
      state = col_character(),
      country = col_character(),
      primary_language = col_character(),
      primary_language_other = col_logical(),
      tax_status_founded = col_character(),
      tax_status_current = col_character(),
      year_founded = col_double(),
      total_employees = col_character(),
      budget_percent_editorial = col_character(),
      budget_percent_revenue_generation = col_character(),
      budget_percent_product_technology = col_character(),
      budget_percent_administration = col_character(),
      products = col_character(),
      products_other = col_character(),
      distribution = col_character(),
      distribution_method_other = col_character(),
      geographic_area = col_character(),
      core_editorial_strategy_characteristics = col_character(),
      core_editorial_strategy_characteristics_other = col_character(),
      coverage_topics = col_character(),
      coverage_topics_other = col_logical(),
      underrepresented_communities = col_character(),
      underrepresented_communities_not_listed = col_character(),
      revenue_streams = col_character(),
      revenue_stream_other = col_logical(),
      revenue_stream_additional_info = col_logical(),
      revenue_stream_largest = col_character(),
      revenue_streams_largest_other = col_character(),
      paywall_or_gateway = col_character(),
      paywall_or_gateway_other = col_logical(),
      advertising_products = col_character(),
      advertising_product_other = col_logical(),
      real_world_impacts = col_character(),
      summary = col_character()
    ))
